-- GuardForce CRM - PostgreSQL normalized schema (SaaS multi-tenant)
-- Run with: psql -d <db_name> -f db/migrations/001_init.sql

-- =========================
-- Identity and Access
-- =========================
-- Global identity: one account per person (email unique platform-wide).
-- Login with verified email OR optional username + password_hash.
-- Tenancy is via tenant_user (same user may belong to multiple tenants).
CREATE TABLE app_user (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  email text UNIQUE NOT NULL,
  username text,
  password_hash text NOT NULL,
  password_updated_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz,
  phone text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT app_user_username_trim CHECK (username IS NULL OR length(trim(username)) > 0)
);

CREATE UNIQUE INDEX ux_app_user_username_lower ON app_user (lower(username))
  WHERE username IS NOT NULL;

CREATE INDEX idx_app_user_email_lower ON app_user (lower(email));

-- =========================
-- Billing / subscription (SaaS)
-- =========================
CREATE TABLE subscription_plan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  name text NOT NULL,
  description text,
  billing_interval text NOT NULL CHECK (billing_interval IN ('monthly', 'yearly')),
  price_amount numeric(12, 2) NOT NULL,
  currency char(3) NOT NULL DEFAULT 'GBP',
  max_users int,
  max_sites int,
  max_officers int,
  features jsonb,
  is_public boolean NOT NULL DEFAULT true,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_plan_public ON subscription_plan (is_public, sort_order);

-- Platform-defined modules / entitlements (linked to plans via subscription_plan_feature)
CREATE TABLE subscription_feature (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  name text NOT NULL,
  description text,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_feature_sort ON subscription_feature (sort_order);

CREATE TABLE subscription_plan_feature (
  subscription_plan_id integer NOT NULL REFERENCES subscription_plan(id) ON DELETE CASCADE,
  subscription_feature_id integer NOT NULL REFERENCES subscription_feature(id) ON DELETE CASCADE,
  PRIMARY KEY (subscription_plan_id, subscription_feature_id)
);

CREATE INDEX idx_subscription_plan_feature_feature ON subscription_plan_feature (subscription_feature_id);

CREATE TABLE tenant (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  status text NOT NULL CHECK (status IN ('active','inactive')),
  subscription_plan_id integer REFERENCES subscription_plan(id) ON DELETE SET NULL,
  subscription_status text NOT NULL DEFAULT 'none' CHECK (
    subscription_status IN ('none', 'trialing', 'active', 'past_due', 'cancelled')
  ),
  subscription_started_at timestamptz,
  subscription_current_period_end timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_subscription_plan_consistent CHECK (
    subscription_status = 'none' OR subscription_plan_id IS NOT NULL
  )
);

CREATE INDEX idx_tenant_subscription_plan ON tenant (subscription_plan_id);

CREATE TABLE role (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  name text NOT NULL
);

CREATE TABLE tenant_user (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  is_owner boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, user_id)
);

CREATE TABLE tenant_user_role (
  tenant_id integer NOT NULL,
  user_id integer NOT NULL,
  role_id integer NOT NULL REFERENCES role(id) ON DELETE RESTRICT,
  PRIMARY KEY (tenant_id, user_id, role_id),
  FOREIGN KEY (tenant_id, user_id) REFERENCES tenant_user(tenant_id, user_id) ON DELETE CASCADE
);

CREATE TABLE branch (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  code text NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, code)
);

-- =========================
-- Shared documents
-- =========================
CREATE TABLE document (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  storage_key text NOT NULL,
  mime_type text,
  file_size bigint,
  uploaded_by integer REFERENCES app_user(id),
  uploaded_at timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- Clients
-- =========================
CREATE TABLE client (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  name text NOT NULL,
  industry text,
  status text NOT NULL CHECK (status IN ('active','inactive')),
  email text,
  phone text,
  address text,
  company_reg_number text,
  vat_number text,
  company_registered_address text,
  website text,
  default_base_rate numeric(10,2),
  started_on date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, name)
);

CREATE TABLE client_contact (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  role_title text,
  email text,
  phone text,
  is_primary boolean NOT NULL DEFAULT false
);

CREATE TABLE client_note (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  note text NOT NULL,
  created_by integer REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE client_document (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  document_id integer NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  doc_type text,
  PRIMARY KEY (tenant_id, client_id, document_id)
);

-- =========================
-- Sites
-- =========================
CREATE TABLE site (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id) ON DELETE RESTRICT,
  branch_id integer REFERENCES branch(id),
  name text NOT NULL,
  address text NOT NULL,
  status text NOT NULL CHECK (status IN ('active','inactive')),
  bookon_email text,
  sop text,
  check_call_enabled boolean NOT NULL DEFAULT false,
  check_call_interval_minutes integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, client_id, name)
);

CREATE TABLE site_contact (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  role_title text,
  email text,
  phone text,
  is_primary boolean NOT NULL DEFAULT false
);

CREATE TABLE site_note (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  note text NOT NULL,
  created_by integer REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE site_document (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  document_id integer NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  doc_type text,
  PRIMARY KEY (tenant_id, site_id, document_id)
);

-- =========================
-- Duty and rates
-- =========================
CREATE TABLE duty_type (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  code text NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (tenant_id, code)
);

CREATE TABLE client_duty_rate (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  duty_type_id integer NOT NULL REFERENCES duty_type(id) ON DELETE CASCADE,
  charge_rate numeric(10,2),
  pay_rate numeric(10,2),
  currency_code char(3) NOT NULL DEFAULT 'GBP',
  PRIMARY KEY (tenant_id, client_id, duty_type_id)
);

CREATE TABLE site_duty_rate (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  duty_type_id integer NOT NULL REFERENCES duty_type(id) ON DELETE CASCADE,
  charge_rate numeric(10,2) NOT NULL,
  pay_rate numeric(10,2),
  currency_code char(3) NOT NULL DEFAULT 'GBP',
  PRIMARY KEY (tenant_id, site_id, duty_type_id)
);

-- =========================
-- Subcontractors
-- =========================
CREATE TABLE subcontractor (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_name text NOT NULL,
  status text NOT NULL CHECK (status IN ('active','inactive','pending')),
  contact_name text,
  email text,
  phone text,
  company_address text,
  company_reg_number text,
  vat_number text,
  notes text,
  UNIQUE (tenant_id, company_name)
);

CREATE TABLE subcontractor_contact (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  subcontractor_id integer NOT NULL REFERENCES subcontractor(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  role_title text,
  email text,
  phone text
);

CREATE TABLE subcontractor_document (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  subcontractor_id integer NOT NULL REFERENCES subcontractor(id) ON DELETE CASCADE,
  document_id integer NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  doc_type text,
  PRIMARY KEY (tenant_id, subcontractor_id, document_id)
);

CREATE TABLE subcontractor_site (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  subcontractor_id integer NOT NULL REFERENCES subcontractor(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  active_from date NOT NULL,
  active_to date,
  PRIMARY KEY (tenant_id, subcontractor_id, site_id, active_from)
);

-- =========================
-- Officers and BS7858
-- =========================
CREATE TABLE officer_type (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  code text NOT NULL,
  name text NOT NULL,
  requires_sia_licence boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (tenant_id, code)
);

CREATE TABLE officer (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_code text,
  full_name text NOT NULL,
  position text,
  avatar_url text,
  nationality text,
  email text,
  phone text,
  status text NOT NULL CHECK (status IN ('active','pending','suspended')),
  compliance_status text NOT NULL CHECK (compliance_status IN ('compliant','pending','expired')),
  officer_type_id integer REFERENCES officer_type(id),
  subcontractor_id integer REFERENCES subcontractor(id),
  date_of_birth date,
  address text,
  ni_number text,
  sia_licence_number text,
  sia_licence_expiry date,
  right_to_work_status text,
  share_code text,
  share_code_expiry date,
  passport_number text,
  passport_country text,
  passport_issue_date date,
  passport_expiry_date date,
  visa_type text,
  visa_number text,
  visa_expiry_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, officer_code)
);

-- Flexible extension fields used by CRM officer detail forms.
-- Keep JSONB to avoid frequent schema churn while preserving tenant + officer scoping.
CREATE TABLE officer_health (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer PRIMARY KEY REFERENCES officer(id) ON DELETE CASCADE,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE officer_appearance (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer PRIMARY KEY REFERENCES officer(id) ON DELETE CASCADE,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE site_preferred_officer (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  site_id integer NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, site_id, officer_id)
);

CREATE TABLE officer_bank_detail (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer PRIMARY KEY REFERENCES officer(id) ON DELETE CASCADE,
  account_name text,
  sort_code text,
  account_number text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE emergency_contact (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  relationship text,
  phone text NOT NULL
);

CREATE TABLE officer_education (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  institution text,
  qualification text,
  date_from text,
  date_to text
);

CREATE TABLE officer_training_cert (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  cert_name text NOT NULL,
  expiry_date date
);

CREATE TABLE officer_document (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  document_id integer NOT NULL REFERENCES document(id) ON DELETE CASCADE,
  doc_type text,
  PRIMARY KEY (tenant_id, officer_id, document_id)
);

CREATE TABLE screening_step (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  code text NOT NULL,
  label text NOT NULL,
  phase text NOT NULL CHECK (phase IN ('initial','full_screening')),
  sort_order integer NOT NULL,
  UNIQUE (tenant_id, code)
);

CREATE TABLE officer_screening_step (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  screening_step_id integer NOT NULL REFERENCES screening_step(id) ON DELETE CASCADE,
  is_done boolean NOT NULL DEFAULT false,
  completed_date date,
  completed_by integer REFERENCES app_user(id),
  PRIMARY KEY (tenant_id, officer_id, screening_step_id)
);

CREATE TABLE employment_reference (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  requested_date date,
  no_of_requests integer NOT NULL DEFAULT 0,
  company text NOT NULL,
  phone text,
  email text,
  employment_from date,
  employment_to date,
  confirmed_from date,
  confirmed_to date,
  comments text,
  status text NOT NULL CHECK (status IN ('pending','contacted','screening_completed','verified'))
);

CREATE TABLE vetting_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  officer_id integer NOT NULL REFERENCES officer(id) ON DELETE CASCADE,
  log_date date NOT NULL,
  action text NOT NULL,
  outcome text,
  created_by integer REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- Scheduling, Calls, Reconciliation
-- =========================
CREATE TABLE shift (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  client_id integer NOT NULL REFERENCES client(id),
  site_id integer NOT NULL REFERENCES site(id),
  duty_type_id integer REFERENCES duty_type(id),
  branch_id integer REFERENCES branch(id),
  officer_id integer REFERENCES officer(id),
  shift_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  break_minutes integer NOT NULL DEFAULT 0,
  planned_hours numeric(6,2),
  charge_rate numeric(10,2),
  pay_rate numeric(10,2),
  currency_code char(3) NOT NULL DEFAULT 'GBP',
  status text NOT NULL CHECK (status IN ('confirmed','pending','unassigned','cancelled')),
  created_by integer REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shift_call_plan (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  shift_id integer PRIMARY KEY REFERENCES shift(id) ON DELETE CASCADE,
  precheck_due_at timestamptz,
  bookon_window_start timestamptz,
  bookon_window_end timestamptz,
  check_call_enabled boolean NOT NULL DEFAULT false,
  check_call_interval_minutes integer
);

CREATE TABLE shift_check_call_window (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  shift_id integer NOT NULL REFERENCES shift(id) ON DELETE CASCADE,
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  sequence_no integer NOT NULL
);

CREATE TABLE shift_call_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  shift_id integer NOT NULL REFERENCES shift(id) ON DELETE CASCADE,
  call_type text NOT NULL CHECK (call_type IN ('precheck','bookon','checkcall')),
  check_window_id integer REFERENCES shift_check_call_window(id),
  attempted_at timestamptz NOT NULL DEFAULT now(),
  outcome text NOT NULL,
  notes text,
  logged_by integer REFERENCES app_user(id)
);

CREATE TABLE shift_timesheet (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  shift_id integer PRIMARY KEY REFERENCES shift(id) ON DELETE CASCADE,
  actual_start timestamptz,
  actual_end timestamptz,
  worked_hours numeric(6,2),
  attendance_status text CHECK (attendance_status IN ('on-time','late','no-show')),
  reconciled boolean NOT NULL DEFAULT false,
  reconciled_at timestamptz,
  reconciled_by integer REFERENCES app_user(id)
);

-- =========================
-- Invoicing
-- =========================
CREATE TABLE invoice (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  invoice_number text NOT NULL,
  client_id integer NOT NULL REFERENCES client(id),
  issue_date date NOT NULL,
  due_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('draft','issued','paid','cancelled')),
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  tax_amount numeric(12,2) NOT NULL DEFAULT 0,
  total_amount numeric(12,2) NOT NULL DEFAULT 0,
  notes text,
  created_by integer REFERENCES app_user(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, invoice_number)
);

CREATE TABLE invoice_shift (
  tenant_id integer NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  invoice_id integer NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
  shift_id integer NOT NULL REFERENCES shift(id) ON DELETE RESTRICT,
  billed_hours numeric(6,2) NOT NULL,
  billed_rate numeric(10,2) NOT NULL,
  line_amount numeric(12,2) NOT NULL,
  PRIMARY KEY (tenant_id, invoice_id, shift_id),
  UNIQUE (shift_id)
);

-- =========================
-- Indexes
-- =========================
CREATE INDEX idx_client_tenant ON client(tenant_id);
CREATE INDEX idx_site_tenant_client ON site(tenant_id, client_id);
CREATE INDEX idx_site_preferred_officer_site ON site_preferred_officer(tenant_id, site_id, sort_order);
CREATE INDEX idx_site_preferred_officer_officer ON site_preferred_officer(tenant_id, officer_id);
CREATE INDEX idx_officer_tenant ON officer(tenant_id);
CREATE INDEX idx_shift_tenant_date_site ON shift(tenant_id, shift_date, site_id);
CREATE INDEX idx_shift_tenant_officer_date ON shift(tenant_id, officer_id, shift_date);
CREATE INDEX idx_shift_timesheet_tenant_reconciled ON shift_timesheet(tenant_id, reconciled);
CREATE INDEX idx_invoice_tenant_client_status ON invoice(tenant_id, client_id, status);
